trigger:
 - main
pool:
  name: default
stages:
  - stage: build
    jobs:
    - job: buildjob
      steps:
        - task: SonarQubePrepare@5
          inputs:
            SonarQube: sonarazure
            projectKey: sandrisai_spring-petclinic
            scannerMode: 'Other'
            configMode: 'manual'

        - task: Maven@4
          inputs:
            mavenPOMFile: 'pom.xml'
            goals: 'clean verify sonar:sonar'
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkArchitectureOption: 'x64'
            jdkVersionOption: 'default'
            publishJUnitResults: true
            

        - task: SonarQubePublish@5
          inputs:
            pollingTimeoutSec: '300'

        - task: CopyFiles@2 
          inputs: 
             Contents: '**'
             TargetFolder: $(build.artifactstagingdirectory)

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
